export const STORE_USERID = 'STORE_USERID';

export const STORE_USERDATA = 'STORE_USERDATA';
//export const STORE_USERIMAGE = 'STORE_USERIMAGE';

export const STORE_MESSAGES_FROM_FIREBASE ='STORE_MESSAGES_FROM_FIREBASE';